#!/bin/bash

################# TWO FLAGS #################

#TODO Unistall flag function
unistall() 
{
    echo -e "***\e[31m Uninstall \e[0m***"
    sudo rm /bin/ali
}
# Verify unistall flag and exit
if [[ "$1" == "--unistall" ]]; then
    unistall
    exit 0
fi


#TODO Shell-enter flag function
shell() 
{
    username=$(whoami)
    sleep 0.25
    ssh $username@localhost -p 2022
}
# Verify  flag and exit
if [[ "$1" == "shell" ]]; then
    shell
    exit 0
fi


#TODO Start alitle
start() 
{
    docker start alitle
}
# Verify  flag and exit
if [[ "$1" == "start" ]]; then
    start
    exit 0
fi


#TODO Start alitle
stop() 
{
    docker stop alitle
}
# Verify  flag and exit
if [[ "$1" == "stop" ]]; then
    stop
    exit 0
fi


################# ONE FLAG #################


#TODO Create flag function
create() 
{
    password=$(echo "ali")
    username=$(whoami)

    ## Create install cript ##
    echo "#!/bin/ash

    #Install base
    apk add curl wget git nano fish shadow sudo openssh-server openrc

    #Setup shell
    chsh root -s /usr/bin/fish
    chsh $username -s /usr/bin/fish

    #Setup ssh
    mv sshd_config /etc/ssh
    ssh-keygen -A
    rc-status
    touch /run/openrc/softlevel
    /etc/init.d/sshd start

    #Setup user (deafult passwd is ali)
    echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel
    adduser -h alitle/$username -D $username
    echo $username:$password | chpasswd
    usermod -aG wheel $username
    chown $username /alitle

    sleep 0.25

    #Remove shits
    rm install.sh

    #Finishing
    echo -e '*** Instalation Complete ***' " >> /tmp/install.sh

    ########
    
    #Setup container
    docker pull alpine:3.19
    docker create -v /home/$USER/Alitle:/alitle --name alitle --network="host" -i alpine:3.19 /bin/ash
    docker start alitle

    #Share
    docker cp /tmp/install.sh alitle:/
    docker cp /opt/ali/conf/sshd_config alitle:/
    docker cp /opt/ali/bin/pfetch alitle:/bin
    docker exec alitle chmod +x install.sh
    docker exec alitle ./install.sh

    rm /tmp/install.sh
}
# Verify create flag and exit
if [[ "$1" == "-c" ]]; then
    create
    exit 0
fi


#TODO Remove alitle
remove() 
{
    docker stop alitle
    docker rm alitle
}
# Verify  flag and exit
if [[ "$1" == "-d" ]]; then
    remove
    exit 0
fi



################# THE MUNDANE #################
#TODO Shell-enter flag function
v() 
{
    echo "Testing"
}
# Verify  flag and exit
if [[ "$1" == "-v" ]]; then
    v
    exit 0
fi

##NEXT FUNC HELP -h